project:
  type: website
  output-dir: docs

website:
  title: "David Yang Shu | Research"
  image: "preview.png"
  site-url: https://davidyangshu.github.io/research/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/index.qmd
        text: CV
      - href: publications/index.qmd
        text: Publications
  twitter-card: true
  open-graph: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-after-body:
      - text: |
          <script data-goatcounter="https://0112358.goatcounter.com/count" 
          async src="//gc.zgo.at/count.js"></script>
