project:
  type: website
  output-dir: docs

website:
  site-url: https://davidyangshu.github.io/research/
  title: "David Yang Shu | Research"
  image: "preview.png"
  google-analytics:
    tracking-id: "G-J1888H1VEP"
    anonymize-ip: true
    storage: none
    version: 3
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/index.qmd
        text: CV
      - href: publications/index.qmd
        text: Publications
  twitter-card: true
  open-graph: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true