project:
  type: website
  output-dir: docs

website:
  title: "David Yang Shu | Research"
  google-analytics: 
    tracking-id: "G-J1888H1VEP"
    anonymize-ip: true
    storage: none
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/index.qmd
        text: CV
      - href: publications/index.qmd
        text: Publications

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true